pipeline {
    agent any

    tools {
        nodejs "Node16"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/anusuyadevi-005/movierv.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('movierv') {
                    bat "npm install"
                }
            }
        }

        stage('Build') {
            steps {
                dir('movierv') {
                    bat "npm run build"
                }
            }
        }

        stage('Archive') {
            steps {
                dir('movierv') {
                    archiveArtifacts artifacts: 'dist/**', fingerprint: true
                }
            }
        }
    }
}
